// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

// Declared by the compiler. Every context type below names these.
type __Cookies = {
  get(name: string): string | undefined;
  all(): Record<string, string>;
  set(name: string, value: string, options?: __CookieOptions): void;
  delete(name: string, options?: __CookieOptions): void;
  signed: {
    get(name: string): Promise<string | undefined>;
    all(): Promise<Record<string, string>>;
    set(name: string, value: string, options?: __CookieOptions): Promise<void>
  }
};
type __CookieOptions = {
  path?: string;
  domain?: string;
  maxAge?: number;
  expires?: Date;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None'
};

// Declared by the app, in the file each was written in.
type Settings = {
  title: string;
  tagline: string;
  timezone: string;
  locale: string;
  themeMode: 'auto' | 'light' | 'dark';
  fontHeadline: string;
  fontInterface: string;
  bgLight: string;
  inkLight: string;
  linkLight: string;
  bgDark: string;
  inkDark: string;
  linkDark: string;
  dayHeadings: boolean;
  showSource: boolean;
  showTime: boolean;
  rules: boolean;
  density: 'compact' | 'normal' | 'relaxed';
  breakingLight: string;
  breakingDark: string;
  breakingHours: number;
  credit: boolean;
  perPage: number;
  passphraseRounds: number;
};
type Strings = {
  skip: string;
  feed: string;
  signIn: string;
  empty: string;
  emptyInvite: string;
  newer: string;
  older: string;
  morePages: string;
  pageOf: string;
  breaking: string;
  poweredBy: string;
  notFound: string;
  notFoundBody: string;
  backToHeadlines: string;
};
type Member = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
};
type Stack = {
  id: string;
  name: string;
  css: string;
};
type Day = {
  key: string;
  label: string;
  iso: string;
  items: any[];
};
type Article = {
  id: string;
  headline: string;
  url: string;
  source: string;
  publishedAt: string;
  status: 'draft' | 'published';
  flagReason: string | null;
  breakingAt: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
};

/** Properties of `<confirm-button>`, from its <script properties> block. */
export type ConfirmButtonProps = {
  token: string;
  label: string;
  heading: string;
  detail: string;
  note: string;
  confirm: string;
  cancel: string;
  name: string;
  value: string;
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {
  site: Settings;
  scheme: string;
  s: Strings;
  density: {
    leading: string;
    pad: string;
  } | {
    leading: string;
    pad: string;
  } | {
    leading: string;
    pad: string;
  };
  rule: string;
  lang: string;
  dir: 'rtl' | 'ltr';
  headline: string;
  ui: string;
  logo: string | null;
  logoDark: string | null;
};

/** The `ctx` argument of `admin/_layout.html`'s loader. */
export type AdminLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin/_layout.html`. */
export type AdminLayoutData = {
  member: Member;
  path: string;
};

/** The `ctx` argument of `admin-people`'s <script server> loader. */
export type AdminPeopleContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  }, keyof {
    member: Member;
    path: string;
  }> & {
    member: Member;
    path: string;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin-people`'s <script server> block. */
export type AdminPeopleData = {
  people: Member[];
  me: Member;
  errors: Record<string, string>;
  form: {
    email: string;
    name: string;
  };
  secret: string | null;
  secretFor: string | null;
  notice: string | null;
};

/** The `ctx` argument of `admin-settings`'s <script server> loader. */
export type AdminSettingsContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  }, keyof {
    member: Member;
    path: string;
  }> & {
    member: Member;
    path: string;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin-settings`'s <script server> block. */
export type AdminSettingsData = {
  site: Settings;
  zones: string[];
  stacks: Stack[];
  hasLogo: boolean;
  hasLogoDark: boolean;
  logoSrc: string | boolean;
  logoDarkSrc: string | boolean;
  contrast: {
    where: string;
    what: string;
    lc: number;
    need: number;
  }[];
  errors: Record<string, string>;
  complaints: string[];
  saved: boolean;
  notice: string | null;
  maxKb: number;
  accepts: string;
  defaults: Settings;
};

/** The `ctx` argument of `admin-index`'s <script server> loader. */
export type AdminIndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  }, keyof {
    member: Member;
    path: string;
  }> & {
    member: Member;
    path: string;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin-index`'s <script server> block. */
export type AdminIndexData = {
  site: Settings;
  items: {
    when: string;
    id: string;
    headline: string;
    url: string;
    source: string;
    publishedAt: string;
    status: 'draft' | 'published';
    flagReason: string | null;
    breakingAt: string | null;
    createdAt: string;
    updatedAt: string;
    createdBy: string | null;
  }[];
  total: number;
  drafts: number;
  page: number;
  pages: number;
  older: string | null;
  newer: string | null;
  form: {
    headline: string;
    url: string;
    source: string;
    publishedAt: string;
  };
  errors: Record<string, string>;
  warning: string | null;
  posted: string | null;
  now: string;
  checking: boolean;
};

/** The `ctx` argument of `login`'s <script server> loader. */
export type LoginContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `login`'s <script server> block. */
export type LoginData = {
  error: string | null;
  email: string;
  next: string;
};

/** The `ctx` argument of `setup`'s <script server> loader. */
export type SetupContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `setup`'s <script server> block. */
export type SetupData = {
  errors: Record<string, string>;
  email: string;
  name: string;
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  s: Strings;
  urgent: {
    time: string;
    id: string;
    headline: string;
    url: string;
    source: string;
    publishedAt: string;
    status: 'draft' | 'published';
    flagReason: string | null;
    breakingAt: string | null;
    createdAt: string;
    updatedAt: string;
    createdBy: string | null;
  }[];
  pageLabel: string;
  title: string;
  tagline: string;
  headings: boolean;
  showSource: boolean;
  days: Day[];
  items: {
    time: string;
    id: string;
    headline: string;
    url: string;
    source: string;
    publishedAt: string;
    status: 'draft' | 'published';
    flagReason: string | null;
    breakingAt: string | null;
    createdAt: string;
    updatedAt: string;
    createdBy: string | null;
  }[];
  page: number;
  pages: number;
  total: number;
  older: string | null;
  newer: string | null;
};

/** Route params for `/admin/articles/:id`. */
export type AdminArticlesIdParams = { id: string };

/** The `ctx` argument of `admin-articles-_id`'s <script server> loader. */
export type AdminArticlesIdContext = {
  url: string;
  params: {
    id: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  }, keyof {
    member: Member;
    path: string;
  }> & {
    member: Member;
    path: string;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin-articles-_id`'s <script server> block. */
export type AdminArticlesIdData = {
  site: Settings;
  article: Article;
  form: {
    headline: string;
    url: string;
    source: string;
    publishedAt: string;
  };
  errors: Record<string, string>;
  saved: boolean;
  isDraft: boolean;
  isBreaking: boolean;
  stillBreaking: boolean;
};

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: Settings;
    scheme: string;
    s: Strings;
    density: {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    } | {
      leading: string;
      pad: string;
    };
    rule: string;
    lang: string;
    dir: 'rtl' | 'ltr';
    headline: string;
    ui: string;
    logo: string | null;
    logoDark: string | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {
  s: Strings;
};

declare global {
  interface HTMLElementTagNameMap {
    "confirm-button": HTMLElement;
  }
}
